<?php
return array(
    "bodyBackground" => array(
        "value" => "#000000",
        "description" => "Body background",
        "tab" => "general",
        "type" => "color",
    ),
    "textColor" => array(
        "value"  => "#b0b0b0",
        "description" => "Text color",
        "tab" => "general",
        "type" => "color",
    ),
    "textEmboss" => array(
        "value"  => "rgba(0,0,0,0)",
        "description" => "Text emboss",
        "tab" => "general",
        "type" => "color",
    ),
    "linkColor" => array(
        "value"  => "#5e8cba",
        "description" => "Link",
        "tab" => "general",
        "type" => "color",
    ),
    "linkColorHover" => array(
        "value"  => "#94b2d1",
        "description" => "Link (hover)",
        "tab" => "general",
        "type" => "color",
    ),
    "baseFontFamily" => array(
        "value"  => "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
        "description" => "Base font",
        "tab" => "general",
        "type" => "font",
    ),
    "baseFontSize" => array(
        "value"  => "13px",
        "description" => "Base font size",
        "tab" => "general",
        "type" => "size",
    ),
    "tableBackground" => array(
        "value"  => "#000000",
        "description" => "Table background",
        "tab" => "table",
        "type" => "color",
    ),
    "tableLabelBackground" => array(
        "value"  => "#303030",
        "description" => "Table header background",
        "tab" => "table",
        "type" => "color",
    ),
    "tableLabelText" => array(
        "value"  => "#6a6a6a",
        "description" => "Table header text",
        "tab" => "table",
        "type" => "color",
    ),
    "btnPrimaryBackground" => array(
        "value"  => "#5e8cba",
        "description" => "Primary brand color",
        "tab" => "buttons",
        "type" => "color",
    ),
    "btnBackground" => array(
        "value"  => "#2b2b2b",
        "description" => "Button background",
        "tab" => "buttons",
        "type" => "color",
    ),
    "btnBorder" => array(
        "value"  => "#000000",
        "description" => "Button border",
        "tab" => "buttons",
        "type" => "color",
    ),
    "btnTextColor" => array(
        "value"  => "#b0b0b0",
        "description" => "Button text",
        "tab" => "buttons",
        "type" => "color",
    ),
    "inputText" => array(
        "value"  => "#bbb",
        "description" => "Input field text",
        "tab" => "forms",
        "type" => "color",
    ),
    "inputBackground" => array(
        "value"  => "#000000",
        "description" => "Input field background",
        "tab" => "forms",
        "type" => "color",
    ),
    "inputBorder" => array(
        "value"  => "#404040",
        "description" => "Input field border",
        "tab" => "forms",
        "type" => "color",
    ),
    "inputBorderFocus" => array(
        "value"  => "rgba(82,168,236,0.8)",
        "description" => "Input field border (focus)",
        "tab" => "forms",
        "type" => "color",
    ),
    "inputDisabledBackground" => array(
        "value"  => "#303030",
        "description" => "Input field background (disabled)",
        "tab" => "forms",
        "type" => "color",
    ),
    "labelColor" => array(
        "value"  => "#999999",
        "description" => "Field label",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownBackground" => array(
        "value"  => "#000000",
        "description" => "Dropdown list background",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownBorder" => array(
        "value"  => "rgba(255,255,255,0.15)",
        "description" => "Dropdown list border",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownLinkColor" => array(
        "value"  => "#999999",
        "description" => "List item text",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownLinkColorHover" => array(
        "value"  => "#dddddd",
        "description" => "List item text (active/hover)",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownLinkBackgroundHover" => array(
        "value"  => "#003a66",
        "description" => "List item background (active/hover)",
        "tab" => "forms",
        "type" => "color",
    ),
    "placeholderText" => array(
        "value" => "#555",
        "description" => "Input field placeholder text",
        "tab" => "forms",
        "type" => "color",
    ),
    "todayColor" => array(
        "value"  => "#002743",
        "description" => "Today color",
        "tab" => "calendar",
        "type" => "color",
    ),
    "alldayBadgeGradientMiddle" => array(
        "value"  => "#5e8cba",
        "description" => "All-day badge color",
        "tab" => "calendar",
        "type" => "color",
    ),
    "eventImageShadow" => array(
        "value"  => "rgba(0,0,0,0.3)",
        "description" => "Event image shadow",
        "tab" => "calendar",
        "type" => "color",
    ),
    "eventDefaultColor" => array(
        "value"  => "#5e8cba",
        "description" => "Event default color",
        "tab" => "month",
        "type" => "color",
    ),
    "eventDefaultColorHover" => array(
        "value"  => "#94b2d1",
        "description" => "Event default color (hover)",
        "tab" => "month",
        "type" => "color",
    ),
    "eventStubAllDayText" => array(
        "value"  => "#000000",
        "description" => "All-day/multi-day event stub text",
        "tab" => "month",
        "type" => "color",
    ),
    "eventStubAllDayTextShadow" => array(
        "value"  => "rgba(255,255,255,0.4)",
        "description" => "All-day/multi-day event stub text shadow",
        "tab" => "month",
        "type" => "color",
    ),
    "eventBorder" => array(
        "value"  => "#404040",
        "description" => "Event border",
        "tab" => "month",
        "type" => "color",
    ),
    "eventBackground" => array(
        "value"  => "#222222",
        "description" => "Event background",
        "tab" => "month",
        "type" => "color",
    ),
    "eventTimeBackground" => array(
        "value"  => "#000000",
        "description" => "Event time background",
        "tab" => "month",
        "type" => "color",
    ),
    "eventText" => array(
        "value"  => "#b0b0b0",
        "description" => "Event text",
        "tab" => "month",
        "type" => "color",
    ),
    "monthViewDateBackground" => array(
        "value"  => "#001829",
        "description" => "Month view date background",
        "tab" => "month",
        "type" => "color",
    ),
    "dayViewNowMarkerColor" => array(
        "value"  => "#f2c539",
        "description" => "Week/day view now marker",
        "tab" => "month",
        "type" => "color",
    ),
    "agendaDateTitleBorder" => array(
        "value"  => "#35597d",
        "description" => "Date label accent color",
        "tab" => "agenda",
        "type" => "color",
    ),
    "agendaDateTitleBackground" => array(
        "value"  => "#000000",
        "description" => "Date label background",
        "tab" => "agenda",
        "type" => "color",
    ),
    "agendaDateBackground" => array(
        "value"  => "#222222",
        "description" => "Date background",
        "tab" => "agenda",
        "type" => "color",
    ),
    "agendaTodayBackground" => array(
        "value"  => "#040e16",
        "description" => "Today background",
        "tab" => "agenda",
        "type" => "color",
    ),
);
