<?php
return array(
    "bodyBackground" => array(
        "value" => "#ffffff",
        "description" => "Body background",
        "tab" => "general",
        "type" => "color",
    ),
    "textColor" => array(
        "value"  => "#333333",
        "description" => "Text color",
        "tab" => "general",
        "type" => "color",
    ),
    "textEmboss" => array(
        "value"  => "#ffffff",
        "description" => "Text emboss",
        "tab" => "general",
        "type" => "color",
    ),
    "linkColor" => array(
        "value"  => "#3d6b99",
        "description" => "Link",
        "tab" => "general",
        "type" => "color",
    ),
    "linkColorHover" => array(
        "value"  => "#335980",
        "description" => "Link (hover)",
        "tab" => "general",
        "type" => "color",
    ),
    "baseFontFamily" => array(
        "value"  => "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
        "description" => "Base font",
        "tab" => "general",
        "type" => "font",
    ),
    "baseFontSize" => array(
        "value"  => "13px",
        "description" => "Base font size",
        "tab" => "general",
        "type" => "size",
    ),
    "tableBackground" => array(
        "value"  => "#ffffff",
        "description" => "Table background",
        "tab" => "table",
        "type" => "color",
    ),
    "tableLabelBackground" => array(
        "value"  => "#f5f5f5",
        "description" => "Table header background",
        "tab" => "table",
        "type" => "color",
    ),
    "tableLabelText" => array(
        "value"  => "#9e9e9e",
        "description" => "Table header text",
        "tab" => "table",
        "type" => "color",
    ),
    "btnPrimaryBackground" => array(
        "value"  => "#6dbb4f",
        "description" => "Primary brand color",
        "tab" => "buttons",
        "type" => "color",
    ),
    "btnBackground" => array(
        "value"  => "#ffffff",
        "description" => "Button background",
        "tab" => "buttons",
        "type" => "color",
    ),
    "btnBorder" => array(
        "value"  => "#cccccc",
        "description" => "Button border",
        "tab" => "buttons",
        "type" => "color",
    ),
    "btnTextColor" => array(
        "value"  => "#333333",
        "description" => "Button text",
        "tab" => "buttons",
        "type" => "color",
    ),
    "inputText" => array(
        "value"  => "#555",
        "description" => "Input field text",
        "tab" => "forms",
        "type" => "color",
    ),
    "inputBackground" => array(
        "value"  => "#ffffff",
        "description" => "Input field background",
        "tab" => "forms",
        "type" => "color",
    ),
    "inputBorder" => array(
        "value"  => "#cccccc",
        "description" => "Input field border",
        "tab" => "forms",
        "type" => "color",
    ),
    "inputBorderFocus" => array(
        "value"  => "rgba(82,168,236,0.8)",
        "description" => "Input field border (focus)",
        "tab" => "forms",
        "type" => "color",
    ),
    "inputDisabledBackground" => array(
        "value"  => "#eeeeee",
        "description" => "Input field background (disabled)",
        "tab" => "forms",
        "type" => "color",
    ),
    "labelColor" => array(
        "value"  => "#aaaaaa",
        "description" => "Field label",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownBackground" => array(
        "value"  => "#ffffff",
        "description" => "Dropdown list background",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownBorder" => array(
        "value"  => "rgba(0,0,0,0.15)",
        "description" => "Dropdown list border",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownLinkColor" => array(
        "value"  => "#333333",
        "description" => "List item text",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownLinkColorHover" => array(
        "value"  => "#262626",
        "description" => "List item text (active/hover)",
        "tab" => "forms",
        "type" => "color",
    ),
    "dropdownLinkBackgroundHover" => array(
        "value"  => "#f5f5f5",
        "description" => "List item background (active/hover)",
        "tab" => "forms",
        "type" => "color",
    ),
    "placeholderText" => array(
        "value" => "#999999",
        "description" => "Input field placeholder text",
        "tab" => "forms",
        "type" => "color",
    ),
    "todayColor" => array(
        "value"  => "#ffffdd",
        "description" => "Today color",
        "tab" => "calendar",
        "type" => "color",
    ),
    "alldayBadgeGradientMiddle" => array(
        "value"  => "#3d6b99",
        "description" => "All-day badge color",
        "tab" => "calendar",
        "type" => "color",
    ),
    "eventImageShadow" => array(
        "value"  => "rgba(0,0,0,0.4)",
        "description" => "Event image shadow",
        "tab" => "calendar",
        "type" => "color",
    ),
    "eventDefaultColor" => array(
        "value"  => "#3d6b99",
        "description" => "Event default color",
        "tab" => "month",
        "type" => "color",
    ),
    "eventDefaultColorHover" => array(
        "value"  => "#335980",
        "description" => "Event default color (hover)",
        "tab" => "month",
        "type" => "color",
    ),
    "eventStubAllDayText" => array(
        "value"  => "#ffffff",
        "description" => "All-day/multi-day event stub text",
        "tab" => "month",
        "type" => "color",
    ),
    "eventStubAllDayTextShadow" => array(
        "value"  => "rgba(0,0,0,0.4)",
        "description" => "All-day/multi-day event stub text shadow",
        "tab" => "month",
        "type" => "color",
    ),
    "eventBorder" => array(
        "value"  => "#cccccc",
        "description" => "Event border",
        "tab" => "month",
        "type" => "color",
    ),
    "eventBackground" => array(
        "value"  => "#ffffff",
        "description" => "Event background",
        "tab" => "month",
        "type" => "color",
    ),
    "eventTimeBackground" => array(
        "value"  => "#eeeeee",
        "description" => "Event time background",
        "tab" => "month",
        "type" => "color",
    ),
    "eventText" => array(
        "value"  => "#333333",
        "description" => "Event text",
        "tab" => "month",
        "type" => "color",
    ),
    "monthViewDateBackground" => array(
        "value"  => "#eaf4ff",
        "description" => "Month view date background",
        "tab" => "month",
        "type" => "color",
    ),
    "dayViewNowMarkerColor" => array(
        "value"  => "#f2c539",
        "description" => "Week/day view now marker",
        "tab" => "month",
        "type" => "color",
    ),
    "agendaDateTitleBorder" => array(
        "value"  => "#6689AC",
        "description" => "Date label accent color",
        "tab" => "agenda",
        "type" => "color",
    ),
    "agendaDateTitleBackground" => array(
        "value"  => "#ffffff",
        "description" => "Date label background",
        "tab" => "agenda",
        "type" => "color",
    ),
    "agendaDateBackground" => array(
        "value"  => "#f2f2f2",
        "description" => "Date background",
        "tab" => "agenda",
        "type" => "color",
    ),
    "agendaTodayBackground" => array(
        "value"  => "#f4f4bf",
        "description" => "Today background",
        "tab" => "agenda",
        "type" => "color",
    ),
);
